// chatName
// isGroupChat
// users
// latestMessage
// groupAdmin

const mongoose = require('mongoose');

const chatModel = mongoose.Schema(
    {
        // Trim : true --> No trailing spaces in the name
        chatName:{type:String,trin:true},
        isGroupChat:{type:Boolean,default:false},
        users:[
            {
                // This means that this attribute will be of type ObjectId which will be generated by the database
                // ref --> means that the ObectId's will be stored for Users
                type:mongoose.Schema.Types.ObjectId,
                ref:"User",
            },
        ],
        // This thing will be displayed on top of chat in every chat
        latestMessage:{
            // Like users this will contain the id which is generated by the databse
            // the id will be taken from Message model
            type:mongoose.Schema.Types.ObjectId,
            ref:"Message",
        },
        groupAdmin:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
        },
    },
    {
        timestamps:true,
    }
);

const Chat = mongoose.model('Chat',chatModel);

module.exports = Chat;